import type { Metadata } from 'next';
import { marcellus, ibmPlexSans } from '@/assets/fonts';
import './globals.scss';
import Button from '@/components/Button';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${marcellus.variable} ${ibmPlexSans.variable} p-5 antialiased`}
      >
        <Button label="Agendar" variant="accent" />
        {/*  <Button label="Agendar" variant="danger" />
        <Button label="Agendar" variant="outline" /> */}
        {children}
      </body>
    </html>
  );
}
